version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: checkpoint
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: checkpoint_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
