definitions:
  communication.AddGameToUserRequest:
    properties:
      game_id:
        type: integer
      review:
        maxLength: 500
        type: string
      score:
        maximum: 100
        minimum: 0
        type: integer
      status:
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
    required:
    - game_id
    type: object
  communication.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  communication.RegisterUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  description: Checkpoint API Docs.
  title: Checkpoint API
  version: "1.0"
paths:
  /games:
    get:
      description: Get a list of games
      operationId: get-games
      parameters:
      - description: Page index
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      - description: Query for search
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get games
      tags:
      - Games
  /login:
    post:
      description: Login user
      operationId: login
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/communication.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login
      tags:
      - Authentication
  /user/games:
    post:
      description: Add a game to the user's collection
      parameters:
      - description: Game data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/communication.AddGameToUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Add game to user
      tags:
      - User
  /user/profile:
    get:
      description: Get user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - User
    put:
      consumes:
      - multipart/form-data
      description: Update user profile details like bio, avatar etc.
      parameters:
      - description: User Bio
        in: formData
        name: bio
        type: string
      - description: User Avatar
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Update user details
      tags:
      - User
  /users:
    post:
      description: Register user in the database
      operationId: register-user
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/communication.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Register user
      tags:
      - Authentication
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
